name: 'Canary Deployment'

# Controls when the action will run
on:
  # Triggers the workflow on pull request events but only for the master branch
  pull_request_target:
    types: [opened, reopened]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs: 
  canary-deployment:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-region: us-east-2
          role-to-assume: arn:aws:iam::607531995438:role/udacity-github-actions
          role-duration-seconds: 1200
          role-skip-session-tagging: true

      - name: Run Canary Deployment
        run: |
          aws eks --region us-east-2 update-kubeconfig --name udacity-cluster
          kubectl config use-context arn:aws:eks:us-east-2:607531995438:cluster/udacity-cluster
          ./starter/apps/canary/canary.sh